name: basic
description: Basic example showcasing SpriteWidget
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sprite: ^3.0.2
  cupertino_icons: ^1.0.5

dev_dependencies:
  lints: ^5.0.0

dependency_overrides:
  flutter_sprite:
    path: ../../

flutter:
  uses-material-design: true
  assets:
    - asset/swords_man/
    - asset/spritesheet/
    - asset/mangotree/
    - asset/turkey/
    - asset/mirrored/
    - asset/blood/
