name: flutter_sprite
description: Spritesheet support for Flutter
version: 1.0.0
homepage: https://github.com/tejainece/flutter_sprite

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0
  image: ^2.1.19
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
