name: flutter_sprite
description: Spritesheet support for Flutter
version: 3.0.5
homepage: https://github.com/tejainece/flutter_sprite

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  image: ^4.0.13
  cupertino_icons: ^1.0.5

dev_dependencies:

flutter:
  uses-material-design: true
